Kanji.find_or_create_by_id(1, image: 'kanji/01.png', meaning: 'słońce, dzień', strokes: 4, reading: 'hi', hiragana: 'ひ', story: 'Za oknem widać DZIEŃ i świecące SŁOŃCE.')
Kanji.find_or_create_by_id(2, image: 'kanji/02.png', meaning: 'drzewo', strokes: 4, reading: 'ki', hiragana: 'き', story: 'Pionowa linia jest pniem DRZEWA pozostałe jego gałęziami.')
Kanji.find_or_create_by_id(3, image: 'kanji/03.png', meaning: 'wschód', strokes: 8, reading: 'higashi', hiragana: 'ひがし', story: 'Słońce WSCHODZĄCE na tle drzewa.')
Kanji.find_or_create_by_id(4, image: 'kanji/04.png', meaning: 'las', strokes: 12, reading: 'mori', hiragana: 'もり', story: 'W LESIE jest dużo drzew.')
Kanji.find_or_create_by_id(5, image: 'kanji/05.png', meaning: 'ogień', strokes: 4, reading: 'hi', hiragana: 'ひ', story: 'Osoba w OGNIU machająca rękami.')
Kanji.find_or_create_by_id(6, image: 'kanji/06.png', meaning: 'pożar', strokes: 12, reading: 'moeru', hiragana: 'もえる', story: 'Palące się drzewa to POŻAR.')
Kanji.find_or_create_by_id(7, image: 'kanji/07.png', meaning: 'odopczywać', strokes: 6, reading: 'yasumu', hiragana: 'もえる', story: 'Człowiek leży pod drzewam i ODPOCZYWA.')
Kanji.find_or_create_by_id(8, image: 'kanji/08.png', meaning: 'brama', strokes: 10, reading: 'mon', hiragana: 'もん', story: 'Ma kształt otwartej BRAMY.')
Kanji.find_or_create_by_id(9, image: 'kanji/09.png', meaning: 'pytać', strokes: 13, reading: 'tou', hiragana: 'とう', story: 'Stanąć w bramie i zadać PYTANIE o wejście.')
Kanji.find_or_create_by_id(10, image: 'kanji/10.png', meaning: 'góra', strokes: 3, reading: 'yama', hiragana: 'やま', story: 'GÓRA z trzema szczytami.')
Kanji.find_or_create_by_id(11, image: 'kanji/11.png', meaning: 'wychodzić', strokes: 5, reading: 'deru', hiragana: 'でる', story: 'Góra WYCHODZI zza góry.')
