Kanji.find(1).radicals << Radical.where(sign: '日')
Kanji.find(2).radicals << Radical.where(sign: '木')
Kanji.find(3).radicals << Radical.where(sign: '木')
Kanji.find(3).radicals << Radical.where(sign: '日')
Kanji.find(4).radicals << Radical.where(sign: '木')
Kanji.find(5).radicals << Radical.where(sign: '火 (灬)')
Kanji.find(6).radicals << Radical.where(sign: '火 (灬)')
Kanji.find(6).radicals << Radical.where(sign: '木')
Kanji.find(7).radicals << Radical.where(sign: '木')
Kanji.find(7).radicals << Radical.where(sign: '人 (亻,𠆢)')
Kanji.find(8).radicals << Radical.where(sign: '門')
Kanji.find(9).radicals << Radical.where(sign: '門')
Kanji.find(9).radicals << Radical.where(sign: '口')
Kanji.find(10).radicals << Radical.where(sign: '山')
Kanji.find(11).radicals << Radical.where(sign: '山')