Radical.find_or_create_by_sign('一', strokes: 1, hiragana: 'いち', reading: 'ichi', meaning: 'one')
Radical.find_or_create_by_sign('丨', strokes: 1, hiragana: 'ぼう', reading: 'bō', meaning: 'line')
Radical.find_or_create_by_sign('丶', strokes: 1, hiragana: 'てん', reading: 'ten ', meaning: 'dot')
Radical.find_or_create_by_sign('丿', strokes: 1, hiragana: 'の', reading: 'no ', meaning: 'bend')
Radical.find_or_create_by_sign('乙 (乚)', strokes: 1, hiragana: 'おつ', reading: 'otsu', meaning: 'second, latter')
Radical.find_or_create_by_sign('亅', strokes: 1, hiragana: 'はねぼう', reading: 'hanebō', meaning: 'hook')
Radical.find_or_create_by_sign('二', strokes: 2, hiragana: 'ふた', reading: 'futa', meaning: 'two')
Radical.find_or_create_by_sign('亠', strokes: 2, hiragana: 'なべぶた', reading: 'nabebuta', meaning: 'lid')
Radical.find_or_create_by_sign('人 (亻,𠆢)', strokes: 2, hiragana: 'ひと', reading: 'hito', meaning: 'human')
Radical.find_or_create_by_sign('儿', strokes: 2, hiragana: 'にんにょう', reading: 'ninnyō', meaning: 'legs')
Radical.find_or_create_by_sign('入 (𠆢)', strokes: 2, hiragana: 'いる', reading: 'iru ', meaning: 'enter')
Radical.find_or_create_by_sign('八 (ハ)', strokes: 2, hiragana: 'はちがしら', reading: 'hachigashira ', meaning: 'eight')
Radical.find_or_create_by_sign('冂', strokes: 2, hiragana: 'まきがまえ', reading: 'makigamae', meaning: 'upside down box')
Radical.find_or_create_by_sign('冖', strokes: 2, hiragana: 'わかんむり', reading: 'wakanmuri', meaning: 'cover')
Radical.find_or_create_by_sign('冫', strokes: 2, hiragana: 'にすい', reading: 'nisui', meaning: 'ice')
Radical.find_or_create_by_sign('几', strokes: 2, hiragana: 'つくえ', reading: 'tsukue ', meaning: 'desk, table')
Radical.find_or_create_by_sign('凵', strokes: 2, hiragana: 'うけばこ', reading: 'ukebako ', meaning: 'container, open mouth')
Radical.find_or_create_by_sign('刀 (刂,⺈)', strokes: 2, hiragana: 'かたな', reading: 'katana ', meaning: 'knife, sword')
Radical.find_or_create_by_sign('力', strokes: 2, hiragana: 'ちから', reading: 'chikara', meaning: 'power, force')
Radical.find_or_create_by_sign('勹', strokes: 2, hiragana: 'つつみがまえ', reading: 'tsutsumigamae ', meaning: 'wrap, embrace')
Radical.find_or_create_by_sign('匕', strokes: 2, hiragana: 'さじのひ', reading: 'sajinohi', meaning: 'spoon')
Radical.find_or_create_by_sign('匚', strokes: 2, hiragana: 'はこがまえ', reading: 'hakogamae', meaning: 'box')
Radical.find_or_create_by_sign('亡 (匸)', strokes: 3, hiragana: 'かくしがまえ', reading: 'kakushigamae', meaning: 'dead, gone')
Radical.find_or_create_by_sign('十', strokes: 2, hiragana: 'じゅう', reading: 'jū ', meaning: 'ten, complete')
Radical.find_or_create_by_sign('卜 (⼘,⺊)', strokes: 2, hiragana: 'ぼくのと', reading: 'bokunoto', meaning: 'divination')
Radical.find_or_create_by_sign('卩 (㔾)', strokes: 2, hiragana: 'ふしづくり', reading: 'fushidzukuri ', meaning: 'seal')
Radical.find_or_create_by_sign('厂', strokes: 2, hiragana: 'がんだれ', reading: 'gandare ', meaning: 'cliff')
Radical.find_or_create_by_sign('厶', strokes: 2, hiragana: 'む', reading: 'mu ', meaning: 'private')
Radical.find_or_create_by_sign('又', strokes: 2, hiragana: 'また', reading: ' mata', meaning: 'again, right hand')
Radical.find_or_create_by_sign('口', strokes: 3, hiragana: 'くち', reading: 'kuchi ', meaning: 'mouth, opening')
Radical.find_or_create_by_sign('囗', strokes: 3, hiragana: 'くにがまえ', reading: 'kunigamae', meaning: 'enclosure')
Radical.find_or_create_by_sign('土', strokes: 3, hiragana: 'つち', reading: 'tsuchi', meaning: 'earth')
Radical.find_or_create_by_sign('士', strokes: 3, hiragana: 'さむらい', reading: 'samurai ', meaning: 'scholar, bachelor')
Radical.find_or_create_by_sign('夂 (夊)', strokes: 3, hiragana: 'ふゆがしら', reading: 'fuyugashira', meaning: 'winter')
Radical.find_or_create_by_sign('夕', strokes: 3, hiragana: 'ゆうべ', reading: 'yūbe ', meaning: 'evening, sunset')
Radical.find_or_create_by_sign('大', strokes: 3, hiragana: 'だい', reading: 'dai ', meaning: 'big, very')
Radical.find_or_create_by_sign('女', strokes: 3, hiragana: 'おんな', reading: 'onna ', meaning: 'woman, female')
Radical.find_or_create_by_sign('子', strokes: 3, hiragana: 'こ', reading: 'ko ', meaning: 'child, seed')
Radical.find_or_create_by_sign('宀', strokes: 3, hiragana: 'うかんむり', reading: 'ukanmuri ', meaning: 'roof')
Radical.find_or_create_by_sign('寸', strokes: 3, hiragana: 'すん', reading: 'sun ', meaning: 'sun (unit of measurement)')
Radical.find_or_create_by_sign('小 (⺌, ⺍)', strokes: 3, hiragana: 'ちいさい', reading: 'chīsai', meaning: 'small, insignificant')
Radical.find_or_create_by_sign('尢 (尤,尣)', strokes: 3, hiragana: 'まげあし', reading: 'mageashi', meaning: 'lame')
Radical.find_or_create_by_sign('尸', strokes: 3, hiragana: 'しかばね', reading: 'shikabane ', meaning: 'corpse')
Radical.find_or_create_by_sign('屮', strokes: 3, hiragana: 'てつ', reading: 'tetsu ', meaning: 'sprout')
Radical.find_or_create_by_sign('山', strokes: 3, hiragana: 'やま', reading: 'yama', meaning: 'mountain')
Radical.find_or_create_by_sign('巛 (川,巜)', strokes: 3, hiragana: 'かわ', reading: 'kawa', meaning: 'river')
Radical.find_or_create_by_sign('工', strokes: 3, hiragana: 'たくみ', reading: 'takumi ', meaning: 'work')
Radical.find_or_create_by_sign('已 (己,巳)', strokes: 3, hiragana: 'おのれ', reading: 'onore', meaning: 'oneself')
Radical.find_or_create_by_sign('巾', strokes: 3, hiragana: 'はば', reading: 'haba', meaning: 'turban, scarf')
Radical.find_or_create_by_sign('干', strokes: 3, hiragana: 'ほし', reading: 'hoshi ', meaning: 'dry')
Radical.find_or_create_by_sign('幺', strokes: 3, hiragana: 'いとがしら', reading: 'itogashira ', meaning: 'short thread')
Radical.find_or_create_by_sign('广', strokes: 3, hiragana: 'まだれ', reading: 'madare', meaning: 'dotted cliff')
Radical.find_or_create_by_sign('廴', strokes: 3, hiragana: 'いんにょう', reading: 'innyō', meaning: 'long stride')
Radical.find_or_create_by_sign('廾', strokes: 3, hiragana: 'にじゅうあし', reading: 'nijūashi', meaning: 'two hands, twenty')
Radical.find_or_create_by_sign('弋', strokes: 3, hiragana: 'しきがまえ', reading: 'shikigamae', meaning: 'ceremony, shoot, arrow')
Radical.find_or_create_by_sign('弓', strokes: 3, hiragana: 'ゆみ', reading: 'yumi', meaning: 'bow')
Radical.find_or_create_by_sign('彐 (彑)', strokes: 3, hiragana: 'けいがしら', reading: 'keigashira', meaning: "pig's head")
Radical.find_or_create_by_sign('彡', strokes: 3, hiragana: 'さんづくり', reading: 'sandzukuri ', meaning: 'hair, bristle, stubble, beard')
Radical.find_or_create_by_sign('彳', strokes: 3, hiragana: 'ぎょうにんべん', reading: 'gyouninben ', meaning: 'step')
Radical.find_or_create_by_sign('心 (忄,⺗)', strokes: 4, hiragana: 'りっしんべん', reading: 'risshinben', meaning: 'heart')
Radical.find_or_create_by_sign('戈', strokes: 4, hiragana: 'かのほこ', reading: 'kanohoko', meaning: 'spear, halberd')
Radical.find_or_create_by_sign('戸 (戶,户)', strokes: 4, hiragana: 'とびらのと', reading: 'tobiranoto ', meaning: 'door, house')
Radical.find_or_create_by_sign('手 (扌,龵)', strokes: 4, hiragana: 'て', reading: 'te ', meaning: 'hand')
Radical.find_or_create_by_sign('支', strokes: 4, hiragana: 'しにょう', reading: 'shinyō', meaning: 'branch')
Radical.find_or_create_by_sign('攵 (攴)', strokes: 4, hiragana: 'のぶん', reading: 'nobun', meaning: 'strike, whip')
Radical.find_or_create_by_sign('文', strokes: 4, hiragana: 'ぶん', reading: 'bun ', meaning: 'script, literature')
Radical.find_or_create_by_sign('斗', strokes: 4, hiragana: 'とます', reading: 'tomasu ', meaning: 'dipper, measuring scoop')
Radical.find_or_create_by_sign('斤', strokes: 4, hiragana: 'おの', reading: 'ono ', meaning: 'axe')
Radical.find_or_create_by_sign('方', strokes: 4, hiragana: 'ほう', reading: 'hō', meaning: 'way, square, raft')
Radical.find_or_create_by_sign('无 (旡)', strokes: 4, hiragana: 'むにょう', reading: 'munyō ', meaning: 'have not')
Radical.find_or_create_by_sign('日', strokes: 4, hiragana: 'にち', reading: 'nichi ', meaning: 'sun, day')
Radical.find_or_create_by_sign('曰', strokes: 4, hiragana: 'いわく', reading: 'iwaku', meaning: 'say')
Radical.find_or_create_by_sign('月 (⺝)', strokes: 4, hiragana: 'つき', reading: 'tsuki ', meaning: 'moon, month; body, flesh')
Radical.find_or_create_by_sign('木', strokes: 4, hiragana: 'き', reading: 'ki ', meaning: 'tree')
Radical.find_or_create_by_sign('欠', strokes: 4, hiragana: 'あくび', reading: 'akubi', meaning: 'yawn, lack')
Radical.find_or_create_by_sign('止', strokes: 4, hiragana: 'とめる', reading: 'tomeru ', meaning: 'stop')
Radical.find_or_create_by_sign('歹 (歺)', strokes: 4, hiragana: 'がつへん', reading: 'gatsuhen', meaning: 'death, decay')
Radical.find_or_create_by_sign('殳', strokes: 4, hiragana: 'ほこつくり', reading: 'hokotsukuri', meaning: 'weapon, lance')
Radical.find_or_create_by_sign('毋 (母,⺟)', strokes: 4, hiragana: 'なかれ', reading: '   nakare, haha', meaning: 'do not, mother')
Radical.find_or_create_by_sign('比', strokes: 4, hiragana: 'くらべる', reading: 'kuraberu', meaning: 'compare, compete')
Radical.find_or_create_by_sign('毛', strokes: 4, hiragana: 'け', reading: 'ke ', meaning: 'fur, hair')
Radical.find_or_create_by_sign('氏', strokes: 4, hiragana: 'うじ', reading: 'uji ', meaning: 'clan')
Radical.find_or_create_by_sign('气', strokes: 4, hiragana: 'きがまえ', reading: 'kigamae ', meaning: 'steam, breath')
Radical.find_or_create_by_sign('水 (氵,氺)', strokes: 4, hiragana: 'みず', reading: 'mizu', meaning: 'water')
Radical.find_or_create_by_sign('火 (灬)', strokes: 4, hiragana: 'ひ', reading: 'hi ', meaning: 'fire')
Radical.find_or_create_by_sign('爪 (爫,⺥,⺤)', strokes: 4, hiragana: 'つめ', reading: 'tsume ', meaning: 'claw, nail, talon')
Radical.find_or_create_by_sign('父', strokes: 4, hiragana: 'ちち', reading: 'chichi', meaning: 'father')
Radical.find_or_create_by_sign('爻', strokes: 4, hiragana: 'コウ',  reading: 'kō', meaning: 'mix, twine, cross')
Radical.find_or_create_by_sign('爿 (丬)', strokes: 4, hiragana: 'しょうへん', reading: 'shōhen ', meaning: 'split wood')
Radical.find_or_create_by_sign('片', strokes: 4, hiragana: 'かた', reading: 'kata', meaning: 'slice')
Radical.find_or_create_by_sign('牙', strokes: 5, hiragana: 'きばへん', reading: 'kibahen ', meaning: 'fang')
Radical.find_or_create_by_sign('牛 (牜, ⺧)', strokes: 4, hiragana: 'うし', reading: 'ushi', meaning: 'cow')
Radical.find_or_create_by_sign('犬 (犭)', strokes: 4, hiragana: 'いぬ', reading: 'inu ', meaning: 'dog')
Radical.find_or_create_by_sign('玄', strokes: 5, hiragana: 'げん', reading: 'gen ', meaning: 'dark, profound')
Radical.find_or_create_by_sign('王 (玉, 玊, ⺩)', strokes: 4, hiragana: 'おう', reading: 'ō', meaning: 'king; ball, jade')
Radical.find_or_create_by_sign('瓜', strokes: 6, hiragana: 'うり', reading: 'uri ', meaning: 'melon')
Radical.find_or_create_by_sign('瓦', strokes: 5, hiragana: 'かわら', reading: 'kawara ', meaning: 'tile')
Radical.find_or_create_by_sign('甘', strokes: 5, hiragana: 'あまい', reading: 'amai ', meaning: 'sweet')
Radical.find_or_create_by_sign('生', strokes: 5, hiragana: 'うまれる', reading: 'umareru ', meaning: 'life')
Radical.find_or_create_by_sign('用 (甩)', strokes: 5, hiragana: 'もちいる', reading: 'mochīru ', meaning: 'use, throw')
Radical.find_or_create_by_sign('田', strokes: 5, hiragana: 'た', reading: 'ta ', meaning: 'field')
Radical.find_or_create_by_sign('疋 (⺪)', strokes: 5, hiragana: 'ひき', reading: 'hiki', meaning: 'bolt of cloth')
Radical.find_or_create_by_sign('疒', strokes: 5, hiragana: 'やまいだれ', reading: 'yamaidare', meaning: 'sickness')
Radical.find_or_create_by_sign('癶', strokes: 5, hiragana: 'はつがしら', reading: 'hatsugashira ', meaning: 'footsteps')
Radical.find_or_create_by_sign('白', strokes: 5, hiragana: 'しろ', reading: 'shiro ', meaning: 'white')
Radical.find_or_create_by_sign('皮', strokes: 5, hiragana: 'けがわ', reading: 'kegawa ', meaning: 'skin')
Radical.find_or_create_by_sign('皿', strokes: 5, hiragana: 'さら', reading: 'sara', meaning: 'dish')
Radical.find_or_create_by_sign('目', strokes: 5, hiragana: 'め', reading: 'me ', meaning: 'eye')
Radical.find_or_create_by_sign('矛', strokes: 5, hiragana: 'むのほこ', reading: 'munohoko', meaning: 'spear, pike')
Radical.find_or_create_by_sign('矢', strokes: 5, hiragana: 'や', reading: 'ya ', meaning: 'arrow')
Radical.find_or_create_by_sign('石', strokes: 5, hiragana: 'いし', reading: 'ishi', meaning: 'stone')
Radical.find_or_create_by_sign('示 (礻)', strokes: 5, hiragana: 'しめす', reading: 'shimesu', meaning: 'altar, display')
Radical.find_or_create_by_sign('禸', strokes: 5, hiragana: 'ぐうのあし', reading: 'gūnoashi ', meaning: 'track')
Radical.find_or_create_by_sign('禾', strokes: 5, hiragana: 'のぎ', reading: 'nogi', meaning: 'twobranch tree')
Radical.find_or_create_by_sign('穴', strokes: 5, hiragana: 'あな', reading: 'ana ', meaning: 'cave')
Radical.find_or_create_by_sign('立', strokes: 5, hiragana: 'たつ', reading: 'tatsu ', meaning: 'stand, erect')
Radical.find_or_create_by_sign('竹 (⺮)', strokes: 6, hiragana: 'たけ', reading: 'take', meaning: 'bamboo')
Radical.find_or_create_by_sign('米', strokes: 6, hiragana: 'こめ', reading: 'kome', meaning: 'rice')
Radical.find_or_create_by_sign('糸 (糹)', strokes: 6, hiragana: 'いと', reading: 'ito ', meaning: 'thread, string')
Radical.find_or_create_by_sign('缶', strokes: 6, hiragana: 'かん', reading: 'kan ', meaning: 'can, earthenware jar')
Radical.find_or_create_by_sign('罒 (网,罓,⺲,⺳)', strokes: 5, hiragana: 'あみがしら', reading: 'amigashira ', meaning: 'net')
Radical.find_or_create_by_sign('羊 (⺶,⺷)', strokes: 6, hiragana: 'ひつじ', reading: 'hitsuji', meaning: 'sheep')
Radical.find_or_create_by_sign('羽', strokes: 6, hiragana: 'はね', reading: 'hane', meaning: 'feather, wing')
Radical.find_or_create_by_sign('耂 (老,⺹)', strokes: 4, hiragana: 'ろう', reading: 'rō', meaning: 'old')
Radical.find_or_create_by_sign('而', strokes: 6, hiragana: 'しかして', reading: 'shikashite', meaning: 'rake, beard')
Radical.find_or_create_by_sign('耒', strokes: 6, hiragana: 'らいすき', reading: 'raisuki ', meaning: 'plow')
Radical.find_or_create_by_sign('耳', strokes: 6, hiragana: 'みみ', reading: 'mimi', meaning: 'ear')
Radical.find_or_create_by_sign('聿 (⺻)', strokes: 6, hiragana: 'ふでづくり', reading: 'fudedzukuri', meaning: 'brush')
Radical.find_or_create_by_sign('肉 (⺼,月)', strokes: 6, hiragana: 'にく', reading: 'niku', meaning: 'meat')
Radical.find_or_create_by_sign('臣', strokes: 7, hiragana: 'しん', reading: 'shin', meaning: 'minister, official')
Radical.find_or_create_by_sign('自', strokes: 6, hiragana: 'みずから', reading: 'mizukara', meaning: 'self (nose=self)')
Radical.find_or_create_by_sign('至', strokes: 6, hiragana: 'いたる', reading: 'itaru', meaning: 'arrive')
Radical.find_or_create_by_sign('臼', strokes: 6, hiragana: 'うす', reading: 'usu ', meaning: 'mortar')
Radical.find_or_create_by_sign('舌', strokes: 6, hiragana: 'した', reading: 'shita ', meaning: 'tongue')
Radical.find_or_create_by_sign('舛', strokes: 7, hiragana: 'ます', reading: 'masu', meaning: 'opposite')
Radical.find_or_create_by_sign('舟', strokes: 6, hiragana: 'ふね', reading: 'fune', meaning: 'boat')
Radical.find_or_create_by_sign('艮', strokes: 6, hiragana: 'うしとら', reading: 'ushitora', meaning: 'stopping')
Radical.find_or_create_by_sign('色', strokes: 6, hiragana: 'いろ', reading: 'iro ', meaning: 'colour, prettiness')
Radical.find_or_create_by_sign('艹 (艸,䒑)', strokes: 3, hiragana: 'くさ', reading: 'kusa', meaning: 'grass, vegetation')
Radical.find_or_create_by_sign('虍', strokes: 6, hiragana: 'とらかんむり', reading: 'torakanmuri ', meaning: 'tiger stripes')
Radical.find_or_create_by_sign('虫', strokes: 6, hiragana: 'むし', reading: 'mushi ', meaning: 'insect')
Radical.find_or_create_by_sign('血', strokes: 6, hiragana: 'ち', reading: 'chi', meaning: 'blood')
Radical.find_or_create_by_sign('行', strokes: 6, hiragana: 'ぎょう', reading: 'gyō', meaning: 'go, do')
Radical.find_or_create_by_sign('衣 (衤)', strokes: 6, hiragana: 'ころも', reading: 'koromo ', meaning: 'clothes')
Radical.find_or_create_by_sign('西 (襾,覀)', strokes: 6, hiragana: 'にし', reading: 'nishi ', meaning: 'west')
Radical.find_or_create_by_sign('見', strokes: 7, hiragana: 'みる', reading: 'miru', meaning: 'see')
Radical.find_or_create_by_sign('角', strokes: 7, hiragana: 'つの', reading: 'tsuno ', meaning: 'horn')
Radical.find_or_create_by_sign('言 (訁)', strokes: 7, hiragana: 'こと', reading: 'koto', meaning: 'speech')
Radical.find_or_create_by_sign('谷', strokes: 7, hiragana: 'たに', reading: 'tani', meaning: 'valley')
Radical.find_or_create_by_sign('豆', strokes: 7, hiragana: 'まめ', reading: 'mame', meaning: 'bean')
Radical.find_or_create_by_sign('豕', strokes: 7, hiragana: 'いのこ', reading: 'inoko', meaning: 'pig')
Radical.find_or_create_by_sign('豸', strokes: 7, hiragana: 'むじな', reading: 'mujina ', meaning: 'cat, badger')
Radical.find_or_create_by_sign('貝', strokes: 7, hiragana: 'かい', reading: 'kai ', meaning: 'shell')
Radical.find_or_create_by_sign('赤', strokes: 7, hiragana: 'あか', reading: 'aka ', meaning: 'red, bare')
Radical.find_or_create_by_sign('走 (赱)', strokes: 7, hiragana: 'はしる', reading: 'hashiru', meaning: 'run')
Radical.find_or_create_by_sign('足 (⻊)', strokes: 7, hiragana: 'あし', reading: 'ashi', meaning: 'foot')
Radical.find_or_create_by_sign('身', strokes: 7, hiragana: 'み', reading: 'mi ', meaning: 'body')
Radical.find_or_create_by_sign('車', strokes: 7, hiragana: 'くるま', reading: 'kuruma ', meaning: 'cart, car')
Radical.find_or_create_by_sign('辛', strokes: 7, hiragana: 'からい', reading: 'karai', meaning: 'spicy, bitter')
Radical.find_or_create_by_sign('辰', strokes: 7, hiragana: 'しんのたつ', reading: 'shinnotatsu', meaning: 'morning')
Radical.find_or_create_by_sign('⻌ (辵,辶)', strokes: 3, hiragana: 'しんにゅう', reading: 'shinnyū', meaning: 'walk')
Radical.find_or_create_by_sign('阝 (邑,⻏)', strokes: 3, hiragana: 'むら', reading: 'mura', meaning: 'town')
Radical.find_or_create_by_sign('酉', strokes: 7, hiragana: 'とり', reading: 'tori', meaning: 'sake')
Radical.find_or_create_by_sign('釆', strokes: 7, hiragana: 'のごめ', reading: 'nogome ', meaning: 'divide, distinguish, choose')
Radical.find_or_create_by_sign('里', strokes: 7, hiragana: 'さと', reading: 'sato', meaning: 'village, mile')
Radical.find_or_create_by_sign('金 (釒)', strokes: 8, hiragana: 'かね', reading: 'kane', meaning: 'metal, gold')
Radical.find_or_create_by_sign('長 (镸)', strokes: 8, hiragana: 'ながい', reading: 'nagai', meaning: 'long, grow; leader')
Radical.find_or_create_by_sign('門', strokes: 8, hiragana: 'もん', reading: 'mon ', meaning: 'gate')
Radical.find_or_create_by_sign('阝 (阜,⻖)', strokes: 3, hiragana: 'ぎふのふ', reading: 'gifunofu', meaning: 'mound, dam')
Radical.find_or_create_by_sign('隶', strokes: 8, hiragana: 'れいづくり', reading: 'reidzukuri ', meaning: 'slave, capture')
Radical.find_or_create_by_sign('隹', strokes: 8, hiragana: 'ふるとり', reading: 'furutori', meaning: 'old bird')
Radical.find_or_create_by_sign('雨 (⻗)', strokes: 8, hiragana: 'あめ', reading: 'ame ', meaning: 'rain')
Radical.find_or_create_by_sign('青 (靑)', strokes: 8, hiragana: 'あお', reading: 'ao', meaning: 'green, blue')
Radical.find_or_create_by_sign('非', strokes: 8, hiragana: 'あらず', reading: 'arazu', meaning: 'wrong')
Radical.find_or_create_by_sign('面 (靣)', strokes: 9, hiragana: 'めん', reading: 'men ', meaning: 'face')
Radical.find_or_create_by_sign('革', strokes: 9, hiragana: 'かくのかわ', reading: 'kakunokawa ', meaning: 'leather, rawhide')
Radical.find_or_create_by_sign('韋', strokes: 10, hiragana: 'なめしがわ', reading: 'nameshigawa', meaning: 'tanned leather')
Radical.find_or_create_by_sign('韭', strokes: 9, hiragana: 'にら', reading: 'nira', meaning: 'leek')
Radical.find_or_create_by_sign('音', strokes: 9, hiragana: 'おと', reading: 'oto ', meaning: 'sound')
Radical.find_or_create_by_sign('頁', strokes: 9, hiragana: 'おおがい', reading: 'ōgai', meaning: 'big shell')
Radical.find_or_create_by_sign('風 (𠘨)', strokes: 9, hiragana: 'かぜ', reading: 'kaze', meaning: 'wind')
Radical.find_or_create_by_sign('飛', strokes: 9, hiragana: 'とぶ', reading: 'tobu', meaning: 'fly')
Radical.find_or_create_by_sign('食 (飠)', strokes: 9, hiragana: 'しょく', reading: 'shyoku ', meaning: 'eat, food')
Radical.find_or_create_by_sign('首', strokes: 9, hiragana: 'くび', reading: 'kubi', meaning: 'neck, head')
Radical.find_or_create_by_sign('香', strokes: 9, hiragana: 'においこう', reading: 'nioikō ', meaning: 'fragrant')
Radical.find_or_create_by_sign('馬', strokes: 10, hiragana: 'うま', reading: 'uma', meaning: 'horse')
Radical.find_or_create_by_sign('骨', strokes: 10, hiragana: 'ほね', reading: 'hone', meaning: 'bone')
Radical.find_or_create_by_sign('高 (髙)', strokes: 10, hiragana: 'たかい', reading: 'takai', meaning: 'tall, high')
Radical.find_or_create_by_sign('髟', strokes: 10, hiragana: 'かみがしら', reading: 'kamigashira', meaning: 'hair')
Radical.find_or_create_by_sign('鬥', strokes: 10, hiragana: 'とうがまえ', reading: 'tōgamae', meaning: 'fight')
Radical.find_or_create_by_sign('鬯', strokes: 10, hiragana: 'ちょう', reading: 'chyō', meaning: 'herbs, sacrificial wine')
Radical.find_or_create_by_sign('鬲', strokes: 10, hiragana: 'かなえ', reading: 'kanae', meaning: 'tripod, cauldron')
Radical.find_or_create_by_sign('鬼', strokes: 10, hiragana: 'おに', reading: 'oni', meaning: 'ghost, demon')
Radical.find_or_create_by_sign('魚', strokes: 11, hiragana: 'うお', reading: 'uo', meaning: 'fish')
Radical.find_or_create_by_sign('鳥', strokes: 11, hiragana: 'とり', reading: 'tori', meaning: 'bird')
Radical.find_or_create_by_sign('鹵', strokes: 11, hiragana: 'ろ', reading: 'ro', meaning: 'salt')
Radical.find_or_create_by_sign('鹿', strokes: 11, hiragana: 'しか', reading: 'shika', meaning: 'deer')
Radical.find_or_create_by_sign('麦 (麥)', strokes: 7, hiragana: 'むぎ', reading: 'mugi', meaning: 'wheat')
Radical.find_or_create_by_sign('麻', strokes: 11, hiragana: 'あさ', reading: 'asa', meaning: 'hemp, flax')
Radical.find_or_create_by_sign('黄 (黃)', strokes: 11, hiragana: 'きいろ', reading: 'kīru', meaning: 'yellow')
Radical.find_or_create_by_sign('黍', strokes: 12, hiragana: 'きび', reading: 'kibi', meaning: 'millet')
Radical.find_or_create_by_sign('黒 (黑)', strokes: 11, hiragana: 'くろ', reading: 'kuro', meaning: 'black')
Radical.find_or_create_by_sign('黹', strokes: 12, hiragana: 'ふつ', reading: 'futsu', meaning: 'embroidery, needlework')
Radical.find_or_create_by_sign('黽', strokes: 13, hiragana: 'べん', reading: 'ben', meaning: 'frog, amphibian')
Radical.find_or_create_by_sign('鼎', strokes: 13, hiragana: 'かなえ', reading: 'kanae', meaning: 'sacrificial tripod')
Radical.find_or_create_by_sign('鼓', strokes: 13, hiragana: 'つづみ', reading: 'tsudzumi', meaning: 'drum')
Radical.find_or_create_by_sign('鼠', strokes: 13, hiragana: 'ねずみ', reading: 'nezumi', meaning: 'rat, mouse')
Radical.find_or_create_by_sign('鼻', strokes: 14, hiragana: 'はな', reading: 'hana', meaning: 'nose')
Radical.find_or_create_by_sign('齊', strokes: 14, hiragana: 'せい', reading: 'sei', meaning: 'even, uniformly')
Radical.find_or_create_by_sign('歯 (齒)', strokes: 12, hiragana: 'は', reading: 'ha', meaning: 'tooth, molar')
Radical.find_or_create_by_sign('竜 (龍)', strokes: 10, hiragana: 'りゅう', reading: 'ryū', meaning: 'dragon')
Radical.find_or_create_by_sign('亀 (龜)', strokes: 11, hiragana: 'かめ', reading: 'kame', meaning: 'turtle, tortoise')
Radical.find_or_create_by_sign('龠', strokes: 17, hiragana: 'やく', reading: 'yaku', meaning: 'flute')